/**
 * divergence_signals_v1 — the observable facts behind the ten DIVERGENCE
 * FACTORS (why two apparently similar startups diverge completely).
 *
 * Deck-only, run in parallel in T0. The model reports what the materials show,
 * with pages; code (engine/divergence) does every count, ratio, cap-table path
 * and level. No psychology, no honesty judgements, no pedigree.
 */
import { DivergenceDraft } from "@/domain/sections";
import { ANALYST_STANDARD, today } from "./common";

export const DIVERGENCE_SIGNALS = { id: "divergence_signals", version: "divergence_signals_v1" } as const;
export const DivergenceSignalsOutput = DivergenceDraft;

export function divergenceSignalsInstructions() {
  return `${ANALYST_STANDARD}

TASK: extract the OBSERVABLE facts that make two similar-looking startups diverge. Today is ${today()}. Report only what the materials show, each with its page. Code computes every number, ratio, ownership path and level from what you report — do not rate, score or summarise. Never describe personality, motives or honesty. Never use the fame of a person, school, employer or investor as evidence of anything. Empty arrays and null are correct answers when the deck shows nothing. Never report an ABSENCE as a signal ("no hiring plan is stated", "switching costs not shown"): leave it out — code lists what is missing.

1. AMBITION — the company the deck says it is building: long-term product scope (SINGLE_WORKFLOW = one job for one buyer; PRODUCT_SUITE = several products sold to the same buyer; PLATFORM = several buyer types or third parties build on it; INFRASTRUCTURE = a layer many companies run on), target geography (where it says it will sell, hire or launch — a market-size figure such as "$38B global TAM" is NOT geography and NOT an ambition signal), market framing, the stated end state (verbatim), and up to 8 signals (product scope, geography, hiring plan and roles, roadmap, market language, round size vs plan), each EXPANSIVE or CONTAINED.
2. CAP TABLE — combined ownership of ACTIVE founders before this round (only if stated); every founder/co-founder named, with status (DEPARTED only if the deck says they left) and stated ownership; option pool total and unallocated; OUTSTANDING SAFEs/notes from BEFORE this round (amount, cap, discount) — not the round being raised now; non-standard terms (participating, >1x, ratchet, redemption, operating vetoes, super-voting); stated investor conflicts.
3. SYNDICATE — every investor/angel named: kind, role in the current round, and ONLY the behaviours stated for this company (follows on in this round, pro-rata/reserves committed, invests at the next stage, bridged or supported in a downturn, introduced customers, helped recruit, active board/operating support, sector specialist, not following on, conflict of interest). A famous name with no stated behaviour gets an empty behaviours list.
4. SURVIVABILITY — if the market takes 24 months longer: the real options the materials support (cut burn, change GTM, alternative monetization, license the technology, services revenue, adjacent segment, non-dilutive funding, strategic partnership, slow down profitably), each DEMONSTRATED (already done / revenue exists), PLAUSIBLE (concrete facts make it feasible) or ASSERTED (only stated); and rigidities that make slowing down hard — only contractual, physical or regulatory constraints (leases, minimum commitments, inventory, licence timelines, a single revenue line); a planned burn is not a commitment and a sales cycle under four months is not a rigidity.
5. MARKET STRUCTURE (not size) — per dimension (fragmentation, buyer concentration, supplier concentration, pricing power, network structure, purchase frequency, switching costs, procurement power, winner-take dynamics, incumbent bundling): FAVORABLE / NEUTRAL / UNFAVORABLE / UNKNOWN for a new entrant, with the fact behind it — UNKNOWN when the materials state nothing specific (the absence of a concentration figure is not FAVORABLE). Stated numbers only: top buyers' share and how many, number of addressable buyers, largest incumbent share.
6. DEPENDENCIES — every critical element the company does NOT control (model provider, cloud, app store, platform API, bank/payment partner, data source, channel partner, licence, supplier/manufacturer, key customer), with what it provides, criticality (CORE = product or revenue stops without it), substitutability, stated switching time and mitigation. One entry per named provider (list each ERP, bank or model provider separately); do not invent generic infrastructure the deck does not mention; if the deck says a provider is used without naming it, write "unnamed". OWNED ASSETS: what it demonstrably controls (distribution, proprietary data, technology/IP, customer relationship, brand/community, own licence).
7. LAND → EXPAND — pricing model; entry-product annual price per customer; largest customer's annual value; every additional module that can be sold to the same customer (LIVE / BETA / ROADMAP / VISION, with stated price); observed expansion inside existing customers.
8. FOCUS — distinct products (LIVE / BETA / ROADMAP; products, not features), customer segments sold to today, countries/regions (ACTIVE / LAUNCHING / PLANNED), acquisition channels actively run.
9. COMPOUNDING LOOPS — loops where each new customer makes the company better (data → better product → better outcomes → more customers; supply → liquidity → demand; integrations; community/content; referral). Break each loop into its links in order; each link DEMONSTRATED only with a measured number, PLAUSIBLE with concrete facts, ASSERTED if only claimed, ABSENT if the deck shows the link does not exist. Empty if none.
10. SCALABILITY — does growth make the company better or more fragile: custom work per customer, implementation effort, services revenue, human-in-the-loop, local team per country, human support per contract, self-serve onboarding, standard product, margin trend (only with margins for two or more periods) — each SCALES / NEUTRAL / FRAGILE, only when the deck shows a fact; typical implementation time in weeks; headcount by function only if stated.`;
}
