import { getDb, schema } from "../src/db/client";
import { desc } from "drizzle-orm";
const db = getDb();
const v = db.select().from(schema.companyVersions).orderBy(desc(schema.companyVersions.createdAt)).get()!;
const c: any = v.canonical, d: any = v.derived;
console.log("ID", c.identity);
console.log("CLASS", JSON.stringify(c.classification));
console.log("METRICS", c.metrics.filter((m:any)=>m.isPrimary).map((m:any)=>`${m.metricKey}=${m.normalizedValue} ${m.state} ${m.calculationMethod} ${m.qualityFlags.join('|')}`).join("\n  "));
console.log("SECURITY", c.analysis.securityFlags);
console.log("CLAIMS verif", c.claims.map((x:any)=>x.verification).reduce((a:any,k:string)=>(a[k]=(a[k]||0)+1,a),{}));
console.log("SOURCES", c.sources.map((s:any)=>`${s.id} ${s.origin} ${s.citationVerified} ${s.url}`).join("\n  "));
console.log("DIMS", d.dimensions.map((x:any)=>`${x.id} ${x.value} [${x.lower}-${x.upper}] cov ${x.coverage}`).join("\n  "));
console.log("MARKET", JSON.stringify(d.market.primary), "deckTam", d.market.deckTamUsd);
console.log("RETURNS", d.returns.inputs.checkUsd, d.returns.inputs.entry, d.returns.scenarios.map((s:any)=>`${s.scenario} exit ${Math.round(s.exitEquityUsd/1e6)}M own ${s.exitOwnershipPct.toFixed(2)} moic ${s.grossMoic?.toFixed(2)} | ${s.basis.slice(0,90)}`).join("\n  "));
console.log("BACKWARDS", d.backwards?.explanation);
console.log("POWERLAW", JSON.stringify(d.powerLaw.components.map((x:any)=>[x.id,x.score])));
console.log("FIN", d.financing.explanation, d.financing.risk);
console.log("REC", d.recommendation.status, d.recommendation.aiSuggested, d.recommendation.rationale.slice(0,300));
console.log("EXC", c.exceptionalStrengths.map((x:any)=>`${x.claim} [${x.rating}]`));
console.log("THESIS", c.thesis?.bet, "\nFATALQ", c.thesis?.fatalQuestion);
console.log("Q", c.questions.map((q:any)=>`${q.tier}: ${q.question}`).join("\n  "));
console.log("NBA", c.nextBestAction);
console.log("SUMMARY", c.executiveSummary);
